name: RevertPlugin
version: '${version}'
main: com.revertplugin.RevertPlugin
api-version: '1.21'
author: artic
description: Автоматический возврат игрока на последний сервер

commands:
  lastserver:
    description: Управление автоматическим возвратом на последний сервер
    usage: /lastserver <disable|enable|status> <player>
    permission: revertplugin.admin
    permission-message: "У вас нет прав на использование этой команды."

permissions:
  revertplugin.admin:
    description: Доступ к командам управления возвратом на последний сервер
    default: op
